// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: proto/csn.proto

package csnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   string  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId      string  `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BwMbps     float64 `protobuf:"fixed64,3,opt,name=bw_mbps,json=bwMbps,proto3" json:"bw_mbps,omitempty"`
	RttMs      float64 `protobuf:"fixed64,4,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	Loss       float64 `protobuf:"fixed64,5,opt,name=loss,proto3" json:"loss,omitempty"`
	DeviceCpu  float64 `protobuf:"fixed64,6,opt,name=device_cpu,json=deviceCpu,proto3" json:"device_cpu,omitempty"`
	BatterySoc float64 `protobuf:"fixed64,7,opt,name=battery_soc,json=batterySoc,proto3" json:"battery_soc,omitempty"`
	EdgeCpu    float64 `protobuf:"fixed64,8,opt,name=edge_cpu,json=edgeCpu,proto3" json:"edge_cpu,omitempty"`
	InputKb    float64 `protobuf:"fixed64,9,opt,name=input_kb,json=inputKb,proto3" json:"input_kb,omitempty"`
	SloP95Ms   float64 `protobuf:"fixed64,10,opt,name=slo_p95_ms,json=sloP95Ms,proto3" json:"slo_p95_ms,omitempty"`
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_csn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_csn_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Context) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Context) GetBwMbps() float64 {
	if x != nil {
		return x.BwMbps
	}
	return 0
}

func (x *Context) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *Context) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *Context) GetDeviceCpu() float64 {
	if x != nil {
		return x.DeviceCpu
	}
	return 0
}

func (x *Context) GetBatterySoc() float64 {
	if x != nil {
		return x.BatterySoc
	}
	return 0
}

func (x *Context) GetEdgeCpu() float64 {
	if x != nil {
		return x.EdgeCpu
	}
	return 0
}

func (x *Context) GetInputKb() float64 {
	if x != nil {
		return x.InputKb
	}
	return 0
}

func (x *Context) GetSloP95Ms() float64 {
	if x != nil {
		return x.SloP95Ms
	}
	return 0
}

type PredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ctx    *Context `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Action string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_csn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_csn_proto_rawDescGZIP(), []int{1}
}

func (x *PredictRequest) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *PredictRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PredictReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MuLatencyMs    float64 `protobuf:"fixed64,1,opt,name=mu_latency_ms,json=muLatencyMs,proto3" json:"mu_latency_ms,omitempty"`
	VarLatency     float64 `protobuf:"fixed64,2,opt,name=var_latency,json=varLatency,proto3" json:"var_latency,omitempty"`
	MuEnergyJ      float64 `protobuf:"fixed64,3,opt,name=mu_energy_j,json=muEnergyJ,proto3" json:"mu_energy_j,omitempty"`
	VarEnergy      float64 `protobuf:"fixed64,4,opt,name=var_energy,json=varEnergy,proto3" json:"var_energy,omitempty"`
	P95ConformalMs float64 `protobuf:"fixed64,5,opt,name=p95_conformal_ms,json=p95ConformalMs,proto3" json:"p95_conformal_ms,omitempty"`
}

func (x *PredictReply) Reset() {
	*x = PredictReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_csn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictReply) ProtoMessage() {}

func (x *PredictReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictReply.ProtoReflect.Descriptor instead.
func (*PredictReply) Descriptor() ([]byte, []int) {
	return file_proto_csn_proto_rawDescGZIP(), []int{2}
}

func (x *PredictReply) GetMuLatencyMs() float64 {
	if x != nil {
		return x.MuLatencyMs
	}
	return 0
}

func (x *PredictReply) GetVarLatency() float64 {
	if x != nil {
		return x.VarLatency
	}
	return 0
}

func (x *PredictReply) GetMuEnergyJ() float64 {
	if x != nil {
		return x.MuEnergyJ
	}
	return 0
}

func (x *PredictReply) GetVarEnergy() float64 {
	if x != nil {
		return x.VarEnergy
	}
	return 0
}

func (x *PredictReply) GetP95ConformalMs() float64 {
	if x != nil {
		return x.P95ConformalMs
	}
	return 0
}

type DecideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ctx             *Context `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	FeasibleActions []string `protobuf:"bytes,2,rep,name=feasible_actions,json=feasibleActions,proto3" json:"feasible_actions,omitempty"`
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_csn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_proto_csn_proto_rawDescGZIP(), []int{3}
}

func (x *DecideRequest) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *DecideRequest) GetFeasibleActions() []string {
	if x != nil {
		return x.FeasibleActions
	}
	return nil
}

type DecideReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChosenAction string `protobuf:"bytes,1,opt,name=chosen_action,json=chosenAction,proto3" json:"chosen_action,omitempty"`
	Explore      bool   `protobuf:"varint,2,opt,name=explore,proto3" json:"explore,omitempty"`
}

func (x *DecideReply) Reset() {
	*x = DecideReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_csn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideReply) ProtoMessage() {}

func (x *DecideReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideReply.ProtoReflect.Descriptor instead.
func (*DecideReply) Descriptor() ([]byte, []int) {
	return file_proto_csn_proto_rawDescGZIP(), []int{4}
}

func (x *DecideReply) GetChosenAction() string {
	if x != nil {
		return x.ChosenAction
	}
	return ""
}

func (x *DecideReply) GetExplore() bool {
	if x != nil {
		return x.Explore
	}
	return false
}

var File_proto_csn_proto protoreflect.FileDescriptor

var file_proto_csn_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x73, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x63, 0x73, 0x6e, 0x22, 0x95, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x77, 0x5f, 0x6d, 0x62, 0x70,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x62, 0x77, 0x4d, 0x62, 0x70, 0x73, 0x12,
	0x15, 0x0a, 0x06, 0x72, 0x74, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x72, 0x74, 0x74, 0x4d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x70, 0x75, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x5f, 0x73, 0x6f, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x6f, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x64,
	0x67, 0x65, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65, 0x64,
	0x67, 0x65, 0x43, 0x70, 0x75, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6b,
	0x62, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x4b, 0x62,
	0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x6c, 0x6f, 0x5f, 0x70, 0x39, 0x35, 0x5f, 0x6d, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73, 0x6c, 0x6f, 0x50, 0x39, 0x35, 0x4d, 0x73, 0x22, 0x48,
	0x0a, 0x0e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x73, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x03, 0x63, 0x74, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x75, 0x5f,
	0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x6d, 0x75, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x61, 0x72, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1e,
	0x0a, 0x0b, 0x6d, 0x75, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6a, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x75, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4a, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x61, 0x72, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x76, 0x61, 0x72, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x28, 0x0a,
	0x10, 0x70, 0x39, 0x35, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x70, 0x39, 0x35, 0x43, 0x6f, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x4d, 0x73, 0x22, 0x5a, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x73, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x03, 0x63, 0x74, 0x78, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x65, 0x61, 0x73,
	0x69, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0f, 0x66, 0x65, 0x61, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x4c, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x6f, 0x73, 0x65,
	0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72,
	0x65, 0x32, 0x3e, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x07, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x63, 0x73, 0x6e, 0x2e,
	0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x63, 0x73, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0x39, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x06,
	0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x63, 0x73, 0x6e, 0x2e, 0x44, 0x65, 0x63,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x63, 0x73, 0x6e,
	0x2e, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x22, 0x5a, 0x20,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x2f, 0x63, 0x73, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x73, 0x6e, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_csn_proto_rawDescOnce sync.Once
	file_proto_csn_proto_rawDescData = file_proto_csn_proto_rawDesc
)

func file_proto_csn_proto_rawDescGZIP() []byte {
	file_proto_csn_proto_rawDescOnce.Do(func() {
		file_proto_csn_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_csn_proto_rawDescData)
	})
	return file_proto_csn_proto_rawDescData
}

var file_proto_csn_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_csn_proto_goTypes = []interface{}{
	(*Context)(nil),        // 0: csn.Context
	(*PredictRequest)(nil), // 1: csn.PredictRequest
	(*PredictReply)(nil),   // 2: csn.PredictReply
	(*DecideRequest)(nil),  // 3: csn.DecideRequest
	(*DecideReply)(nil),    // 4: csn.DecideReply
}
var file_proto_csn_proto_depIdxs = []int32{
	0, // 0: csn.PredictRequest.ctx:type_name -> csn.Context
	0, // 1: csn.DecideRequest.ctx:type_name -> csn.Context
	1, // 2: csn.Predictor.Predict:input_type -> csn.PredictRequest
	3, // 3: csn.Decider.Decide:input_type -> csn.DecideRequest
	2, // 4: csn.Predictor.Predict:output_type -> csn.PredictReply
	4, // 5: csn.Decider.Decide:output_type -> csn.DecideReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_csn_proto_init() }
func file_proto_csn_proto_init() {
	if File_proto_csn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_csn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_csn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_csn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_csn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_csn_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecideReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_csn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_csn_proto_goTypes,
		DependencyIndexes: file_proto_csn_proto_depIdxs,
		MessageInfos:      file_proto_csn_proto_msgTypes,
	}.Build()
	File_proto_csn_proto = out.File
	file_proto_csn_proto_rawDesc = nil
	file_proto_csn_proto_goTypes = nil
	file_proto_csn_proto_depIdxs = nil
}
