# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/csn.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/csn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/csn.proto\x12\x03\x63sn\"\xbc\x01\n\x07\x43ontext\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62w_mbps\x18\x03 \x01(\x01\x12\x0e\n\x06rtt_ms\x18\x04 \x01(\x01\x12\x0c\n\x04loss\x18\x05 \x01(\x01\x12\x12\n\ndevice_cpu\x18\x06 \x01(\x01\x12\x13\n\x0b\x62\x61ttery_soc\x18\x07 \x01(\x01\x12\x10\n\x08\x65\x64ge_cpu\x18\x08 \x01(\x01\x12\x10\n\x08input_kb\x18\t \x01(\x01\x12\x12\n\nslo_p95_ms\x18\n \x01(\x01\";\n\x0ePredictRequest\x12\x19\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x0c.csn.Context\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"}\n\x0cPredictReply\x12\x15\n\rmu_latency_ms\x18\x01 \x01(\x01\x12\x13\n\x0bvar_latency\x18\x02 \x01(\x01\x12\x13\n\x0bmu_energy_j\x18\x03 \x01(\x01\x12\x12\n\nvar_energy\x18\x04 \x01(\x01\x12\x18\n\x10p95_conformal_ms\x18\x05 \x01(\x01\"D\n\rDecideRequest\x12\x19\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x0c.csn.Context\x12\x18\n\x10\x66\x65\x61sible_actions\x18\x02 \x03(\t\"5\n\x0b\x44\x65\x63ideReply\x12\x15\n\rchosen_action\x18\x01 \x01(\t\x12\x0f\n\x07\x65xplore\x18\x02 \x01(\x08\x32>\n\tPredictor\x12\x31\n\x07Predict\x12\x13.csn.PredictRequest\x1a\x11.csn.PredictReply29\n\x07\x44\x65\x63ider\x12.\n\x06\x44\x65\x63ide\x12\x12.csn.DecideRequest\x1a\x10.csn.DecideReplyB\"Z github.com/mulat/csn/proto;csnpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.csn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/mulat/csn/proto;csnpb'
  _globals['_CONTEXT']._serialized_start=25
  _globals['_CONTEXT']._serialized_end=213
  _globals['_PREDICTREQUEST']._serialized_start=215
  _globals['_PREDICTREQUEST']._serialized_end=274
  _globals['_PREDICTREPLY']._serialized_start=276
  _globals['_PREDICTREPLY']._serialized_end=401
  _globals['_DECIDEREQUEST']._serialized_start=403
  _globals['_DECIDEREQUEST']._serialized_end=471
  _globals['_DECIDEREPLY']._serialized_start=473
  _globals['_DECIDEREPLY']._serialized_end=526
  _globals['_PREDICTOR']._serialized_start=528
  _globals['_PREDICTOR']._serialized_end=590
  _globals['_DECIDER']._serialized_start=592
  _globals['_DECIDER']._serialized_end=649
# @@protoc_insertion_point(module_scope)
