// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/csn.proto

package csnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Predictor_Predict_FullMethodName = "/csn.Predictor/Predict"
)

// PredictorClient is the client API for Predictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictorClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
}

type predictorClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictorClient(cc grpc.ClientConnInterface) PredictorClient {
	return &predictorClient{cc}
}

func (c *predictorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, Predictor_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictorServer is the server API for Predictor service.
// All implementations must embed UnimplementedPredictorServer
// for forward compatibility
type PredictorServer interface {
	Predict(context.Context, *PredictRequest) (*PredictReply, error)
	mustEmbedUnimplementedPredictorServer()
}

// UnimplementedPredictorServer must be embedded to have forward compatible implementations.
type UnimplementedPredictorServer struct {
}

func (UnimplementedPredictorServer) Predict(context.Context, *PredictRequest) (*PredictReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedPredictorServer) mustEmbedUnimplementedPredictorServer() {}

// UnsafePredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictorServer will
// result in compilation errors.
type UnsafePredictorServer interface {
	mustEmbedUnimplementedPredictorServer()
}

func RegisterPredictorServer(s grpc.ServiceRegistrar, srv PredictorServer) {
	s.RegisterService(&Predictor_ServiceDesc, srv)
}

func _Predictor_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predictor_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Predictor_ServiceDesc is the grpc.ServiceDesc for Predictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Predictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csn.Predictor",
	HandlerType: (*PredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _Predictor_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/csn.proto",
}

const (
	Decider_Decide_FullMethodName = "/csn.Decider/Decide"
)

// DeciderClient is the client API for Decider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeciderClient interface {
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideReply, error)
}

type deciderClient struct {
	cc grpc.ClientConnInterface
}

func NewDeciderClient(cc grpc.ClientConnInterface) DeciderClient {
	return &deciderClient{cc}
}

func (c *deciderClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideReply, error) {
	out := new(DecideReply)
	err := c.cc.Invoke(ctx, Decider_Decide_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeciderServer is the server API for Decider service.
// All implementations must embed UnimplementedDeciderServer
// for forward compatibility
type DeciderServer interface {
	Decide(context.Context, *DecideRequest) (*DecideReply, error)
	mustEmbedUnimplementedDeciderServer()
}

// UnimplementedDeciderServer must be embedded to have forward compatible implementations.
type UnimplementedDeciderServer struct {
}

func (UnimplementedDeciderServer) Decide(context.Context, *DecideRequest) (*DecideReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedDeciderServer) mustEmbedUnimplementedDeciderServer() {}

// UnsafeDeciderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeciderServer will
// result in compilation errors.
type UnsafeDeciderServer interface {
	mustEmbedUnimplementedDeciderServer()
}

func RegisterDeciderServer(s grpc.ServiceRegistrar, srv DeciderServer) {
	s.RegisterService(&Decider_ServiceDesc, srv)
}

func _Decider_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeciderServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decider_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeciderServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Decider_ServiceDesc is the grpc.ServiceDesc for Decider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Decider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csn.Decider",
	HandlerType: (*DeciderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _Decider_Decide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/csn.proto",
}
